apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mq01-argo
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "100"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: mq01-dev
    server: https://kubernetes.default.svc
  project: default
  source:
    path: environments/dev/mq01/
    repoURL: https://github.com/$GITORG/mq01-ops.git
    targetRevision: main
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Replace=true
