apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/mq-operator.mq01-ns: ''
  name: ibm-licensing-operator-app
  namespace: ibm-common-services
spec:
  channel: v3
  installPlanApproval: Automatic
  name: ibm-licensing-operator-app
  source: opencloud-operators
  sourceNamespace: openshift-marketplace
